{
    "name": "MikroTik Integration",
    "version": "18.0.8.2.0",
    "summary": "Integration with MikroTik routers via RouterOS REST API",
    "description": "Connects Mundo1Telecom Odoo with MikroTik routers for monitoring and management.",
    "author": "Mundo1Telecom",
    "category": "Telecommunications",
    "depends": ["base", "mail", "base_setup", "subscription_oca"],
    "data": [
        "security/groups.xml",
        "security/ir.model.access.csv",
        "data/sequences.xml",
        "views/mikrotik_router_views.xml",
        "views/mikrotik_ppp_profile_views.xml",
        "views/mikrotik_ppp_secret_views.xml",
        "views/mikrotik_queue_simple_views.xml",
        "views/mikrotik_ip_pool_views.xml",
        "views/mikrotik_ip_address_views.xml",
        "views/mikrotik_service_plan_views.xml",
        "views/mikrotik_installation_request_views.xml",
        "views/customer_onboarding_wizard_views.xml",
        "views/res_config_settings_views.xml",
        "views/sale_subscription_views.xml",
        "views/menu.xml",
    ],
    "installable": True,
    "application": True,
    "license": "LGPL-3",
}
